- hosts: leaf1-DC1
  gather_facts: no
  tasks: 
  - name: get management interface properties in JSON format
    eos_command:
      commands: show version | json
      wait_for: result[0].architecture == "i686" 
   
